In [2]:
import numpy as np
import pandas as pd

In [3]:
## 4.2.1 Creating Series and Data Frame

s = pd.Series([2,4,1,-4,'home'], index=['a', 'b', 'c', 'd', 'e'])
# TODO What is the data type of s? Can it be changed ?
# data type is dtype=object
# yes it can be changed. 
# According to the Pandas documentation pandas.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)
# so in here we can define a dtype parameter so the s will have that type if it fits, o/w an error will be raised

In [4]:
data = {'population': [1.5, 1.7, 3.6, 2.4, 2.9], 'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002]}

df = pd.DataFrame(data , columns=['year', 'state', 'population', 'debt'], index=['one', 'two', 'three', 'four', 'five'])

In [5]:
## 4.2.2 Accessing and Modifying

In [6]:
s[['a', 0]]

C:\Users\Kasun\Anaconda3\lib\site-packages\pandas\core\series.py:851: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self.loc[key]

a      2
0    NaN
dtype: object

In [7]:
s.values[2:]

array([1, -4, 'home'], dtype=object)

In [8]:
df[['population', 'state']]

       population   state
one           1.5    Ohio
two           1.7    Ohio
three         3.6    Ohio
four          2.4  Nevada
five          2.9  Nevada

In [9]:
df.population

one      1.5
two      1.7
three    3.6
four     2.4
five     2.9
Name: population, dtype: float64

In [10]:
df.ix[0:,]

C:\Users\Kasun\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

       year   state  population debt
one    2000    Ohio         1.5  NaN
two    2001    Ohio         1.7  NaN
three  2002    Ohio         3.6  NaN
four   2001  Nevada         2.4  NaN
five   2002  Nevada         2.9  NaN

In [11]:
df.ix[2:4:,2]

C:\Users\Kasun\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

three    3.6
four     2.4
Name: population, dtype: float64

In [12]:
df.iloc[2:4:,2]

three    3.6
four     2.4
Name: population, dtype: float64

In [13]:
df.loc['one']

year          2000
state         Ohio
population     1.5
debt           NaN
Name: one, dtype: object

In [14]:
df.debt = 34.67

In [15]:
df.debt = [ df.ix[:,2][i]*5 for i in range(0, df.shape[0])]

C:\Users\Kasun\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

In [16]:
df.head()

       year   state  population  debt
one    2000    Ohio         1.5   7.5
two    2001    Ohio         1.7   8.5
three  2002    Ohio         3.6  18.0
four   2001  Nevada         2.4  12.0
five   2002  Nevada         2.9  14.5

In [17]:
df.tail()

       year   state  population  debt
one    2000    Ohio         1.5   7.5
two    2001    Ohio         1.7   8.5
three  2002    Ohio         3.6  18.0
four   2001  Nevada         2.4  12.0
five   2002  Nevada         2.9  14.5

In [18]:
df.sample(n=5)

       year   state  population  debt
one    2000    Ohio         1.5   7.5
five   2002  Nevada         2.9  14.5
three  2002    Ohio         3.6  18.0
two    2001    Ohio         1.7   8.5
four   2001  Nevada         2.4  12.0

In [19]:
df['newColumn'] = pd.Series(np.random.randn(df.shape[0]),index=df.index)
df

       year   state  population  debt  newColumn
one    2000    Ohio         1.5   7.5   0.449837
two    2001    Ohio         1.7   8.5   0.297224
three  2002    Ohio         3.6  18.0   0.304491
four   2001  Nevada         2.4  12.0   0.666371
five   2002  Nevada         2.9  14.5   0.450370

In [20]:
# 4.2.3 Loading Data from CSV File

In [21]:
df = pd.read_csv('sampleDataSet.csv')
df.shape

(99, 9)

In [22]:
df = pd.read_csv('sampleDataSet.csv', names = ['a','b','c','d','e','f','g','h','i'])
df.shape

(100, 9)

In [23]:
# TODO Comment on results of df . shape ( ) with and without setting names
# Ans: pandas take fisrt row as names, so now data rows are reduced to 99, usually first line denotes fields.
# After we set the names we get 100 data rows because now pandas select csv file as raw data

In [24]:
df = pd.read_csv('sampleDataSet.csv', header= None)
df.shape

# After setting header=None pandas read every row as data rows and automatically numbers fields

(100, 9)

In [25]:
df = pd.read_csv('sampleDataSet.csv', names = ['a','b','c','d','e','f','g','h','i'])

In [26]:
df.isnull().a

0     False
1     False
2     False
3     False
4      True
5      True
6      True
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
      ...
70    False
71    False
72    False
73    False
74    False
75    False
76    False
77    False
78    False
79    False
80    False
81    False
82    False
83    False
84    False
85    False
86    False
87    False
88    False
89    False
90    False
91    False
92    False
93     True
94    False
95    False
96    False
97    False
98    False
99    False
Name: a, Length: 100, dtype: bool

In [27]:
df.isnull().sum()

a    4
b    1
c    0
d    3
e    2
f    2
g    1
h    1
i    1
dtype: int64

In [28]:
df = df[df.isnull().a != True]

In [29]:
df.dropna(axis=0).isnull().sum()

a    0
b    0
c    0
d    0
e    0
f    0
g    0
h    0
i    0
dtype: int64

In [30]:
df.dropna(axis=1)

      a         c
0   5.1  3.500000
1   4.9  3.000000
2   4.7  3.200000
3   4.6  3.100000
7   5.0  3.400000
8   4.4  2.900000
9   4.9  3.100000
10  5.4  3.700000
11  4.8  3.400000
12  4.8  3.000000
13  4.3  3.000000
14  5.8  4.000000
15  5.7  4.400000
16  5.4  3.900000
17  5.1  3.500000
18  5.7  3.800000
19  5.1  3.800000
20  5.4  3.400000
21  5.1  3.700000
22  4.6  3.600000
23  5.1  3.300000
24  4.8  3.400000
25  5.0  3.000000
26  5.0  3.400000
27  5.2  3.500000
28  5.2  3.400000
29  4.7  3.200000
30  4.8  3.100000
31  5.4  3.400000
32  7.0  3.200000
..  ...       ...
69  6.3  2.900000
70  6.5  3.000000
71  7.6  3.000000
72  4.9  2.500000
73  7.3  2.900000
74  6.7  2.500000
75  7.2  3.600000
76  6.5  3.200000
77  6.4  2.700000
78  6.8  3.000000
79  5.7  2.500000
80  5.8  2.800000
81  6.4  3.200000
82  6.5  3.000000
83  7.7  3.800000
84  7.7  2.600000
85  6.0  2.200000
86  6.9  3.200000
87  5.6  2.800000
88  7.7  2.800000
89  6.3  2.700000
90  6.7  3.300000
91  7.2  3.200000
92  6.2  2.800000
94  6.4  2.800000
95  7.2  3.000000
96  7.4  0.333333
97  7.9  3.800000
98  6.4  2.800000
99  6.3  2.800000

[96 rows x 2 columns]

In [31]:
df.dropna(axis=1, how='all')

,a,b,c,d,e,f,g,h,i
0,5.1,0.222222,3.500000,0.625000,1.400000,0.067797,0.20,0.041666667,setosa
1,4.9,0.166667,3.000000,0.416667,1.400000,0.067797,0.20,0.041666667,setosa
2,4.7,0.111111,3.200000,0.500000,1.300000,NaN,0.20,0.041666667,setosa
3,4.6,0.083333,3.100000,0.458333,1.500000,0.084746,0.20,0.041666667,setosa
7,5.0,0.194444,3.400000,NaN,1.500000,0.084746,0.20,0.041666667,setosa
8,4.4,0.027778,2.900000,0.375000,1.400000,0.067797,0.20,0.041666667,setosa
9,4.9,0.166667,3.100000,0.458333,1.500000,0.084746,0.10,0.01,setosa
10,5.4,0.305556,3.700000,0.708333,1.500000,0.084746,0.20,0.041666667,setosa
11,4.8,0.138889,3.400000,0.583333,1.600000,0.101695,0.20,0.041666667,setosa
12,4.8,0.138889,3.000000,0.416667,1.400000,0.067797,0.10,0.01,setosa
13,4.3,0.010000,3.000000,NaN,1.100000,0.016949,0.10,0.01,setosa
14,5.8,0.416667,4.000000,0.833333,1.200000,0.033898,0.20,0.041666667,setosa
15,5.7,0.388889,4.400000,0.999900,1.500000,0.084746,0.40,0.125,setosa
16,5.4,0.305556,3.900000,0.791667,1.300000,0.050847,0.40,0.125,setosa
17,5.1,0.222222,3.500000,0.625000,1.400000,0.067797,0.30,0.083333333,setosa
18,5.7,0.388889,3.800000,0.750000,1.700000,0.118644,0.30,0.083333333,setosa
19,5.1,0.222222,3.800000,0.750000,1.500000,0.084746,0.30,0.083333333,setosa
20,5.4,0.305556,3.400000,0.583333,1.700000,0.118644,0.20,0.041666667,setosa
21,5.1,0.222222,3.700000,0.708333,1.500000,0.084746,0.40,0.125,setosa
22,4.6,0.083333,3.600000,0.666667,1.000000,0.010000,0.20,0.041666667,setosa
23,5.1,0.222222,3.300000,0.541667,1.700000,0.118644,0.50,0.166666667,setosa
24,4.8,0.138889,3.400000,0.583333,1.900000,0.152542,0.20,0.041666667,setosa
25,5.0,0.194444,3.000000,0.416667,1.600000,0.101695,0.20,0.041666667,setosa
26,5.0,0.194444,3.400000,NaN,NaN,0.101695,0.40,0.125,setosa
27,5.2,0.250000,3.500000,0.625000,1.500000,0.084746,0.20,0.041666667,setosa
28,5.2,0.250000,3.400000,0.583333,1.400000,0.067797,0.20,0.041666667,setosa
29,4.7,0.111111,3.200000,0.500000,1.600000,0.101695,0.20,0.041666667,setosa
30,4.8,0.138889,3.100000,0.458333,1.600000,0.101695,0.20,0.041666667,setosa
31,5.4,0.305556,3.400000,0.583333,1.500000,0.084746,0.40,0.125,setosa
32,7.0,0.750000,3.200000,0.500000,4.700000,0.627119,1.40,0.541666667,versicolor
...,...,...,...,...,...,...,...,...,...
69,6.3,0.555556,2.900000,0.375000,5.600000,0.779661,1.80,0.708333333,virginica
70,6.5,0.611111,3.000000,0.416667,5.800000,0.813559,2.20,0.875,virginica
71,7.6,0.916667,3.000000,0.416667,6.600000,0.949153,2.10,0.833333333,virginica
72,4.9,0.166667,2.500000,0.208333,4.500000,0.593220,1.70,0.666666667,virginica
73,7.3,0.833333,2.900000,0.375000,6.300000,0.898305,1.80,0.708333333,virginica
74,6.7,0.666667,2.500000,0.208333,5.800000,0.813559,1.80,0.708333333,virginica
75,7.2,0.805556,3.600000,0.666667,6.100000,0.864407,2.50,0.9999,virginica
76,6.5,0.611111,3.200000,0.500000,5.100000,0.694915,2.00,0.791666667,virginica
77,6.4,0.583333,2.700000,0.291667,5.300000,0.728814,1.90,0.75,virginica
78,6.8,0.694444,3.000000,0.416667,5.500000,0.762712,2.10,0.833333333,virginica
79,5.7,0.388889,2.500000,0.208333,5.000000,0.677966,2.00,0.791666667,virginica
80,5.8,0.416667,2.800000,0.333333,5.100000,0.694915,2.40,0.958333333,virginica
81,6.4,0.583333,3.200000,0.500000,5.300000,0.728814,2.30,0.916666667,virginica
82,6.5,0.611111,3.000000,0.416667,5.500000,0.762712,1.80,0.708333333,virginica
83,7.7,0.944444,3.800000,0.750000,6.700000,0.966102,2.20,0.875,virginica
84,7.7,0.944444,2.600000,0.250000,6.900000,0.999900,2.30,0.916666667,virginica
85,6.0,0.472222,2.200000,0.083333,5.000000,0.677966,1.50,0.583333333,virginica
86,6.9,0.722222,3.200000,0.500000,5.700000,0.796610,2.30,NaN,virginica
87,5.6,0.361111,2.800000,0.333333,4.900000,0.661017,2.00,0.791666667,virginica
88,7.7,0.944444,2.800000,0.333333,6.700000,0.966102,2.00,0.791666667,virginica
89,6.3,0.555556,2.700000,0.291667,4.900000,0.661017,1.80,0.708333333,virginica
90,6.7,0.666667,3.300000,0.541667,5.700000,0.796610,2.10,0.833333333,virginica
91,7.2,0.805556,3.200000,0.500000,6.000000,0.847458,1.80,0.708333333,virginica
92,6.2,0.527778,2.800000,0.333333,4.800000,0.644068,1.80,0.708333333,virginica
94,6.4,0.583333,2.800000,0.333333,5.600000,0.779661,2.10,0.833333333,virginica
95,7.2,0.805556,3.000000,0.416667,5.800000,0.813559,1.60,0.625,virginica
96,7.4,NaN,0.333333,6.100000,0.864407,1.900000,0.75,virginica,NaN
97,7.9,0.999900,3.800000,0.750000,6.400000,0.915254,2.00,0.791666667,virginica
98,6.4,0.583333,2.800000,0.333333,5.600000,0.779661,2.20,0.875,virginica
99,6.3,0.555556,2.800000,0.333333,5.100000,0.694915,1.50,0.583333333,virginica

In [32]:
df.dropna(axis=1, thresh=1)

,a,b,c,d,e,f,g,h,i
0,5.1,0.222222,3.500000,0.625000,1.400000,0.067797,0.20,0.041666667,setosa
1,4.9,0.166667,3.000000,0.416667,1.400000,0.067797,0.20,0.041666667,setosa
2,4.7,0.111111,3.200000,0.500000,1.300000,NaN,0.20,0.041666667,setosa
3,4.6,0.083333,3.100000,0.458333,1.500000,0.084746,0.20,0.041666667,setosa
7,5.0,0.194444,3.400000,NaN,1.500000,0.084746,0.20,0.041666667,setosa
8,4.4,0.027778,2.900000,0.375000,1.400000,0.067797,0.20,0.041666667,setosa
9,4.9,0.166667,3.100000,0.458333,1.500000,0.084746,0.10,0.01,setosa
10,5.4,0.305556,3.700000,0.708333,1.500000,0.084746,0.20,0.041666667,setosa
11,4.8,0.138889,3.400000,0.583333,1.600000,0.101695,0.20,0.041666667,setosa
12,4.8,0.138889,3.000000,0.416667,1.400000,0.067797,0.10,0.01,setosa
13,4.3,0.010000,3.000000,NaN,1.100000,0.016949,0.10,0.01,setosa
14,5.8,0.416667,4.000000,0.833333,1.200000,0.033898,0.20,0.041666667,setosa
15,5.7,0.388889,4.400000,0.999900,1.500000,0.084746,0.40,0.125,setosa
16,5.4,0.305556,3.900000,0.791667,1.300000,0.050847,0.40,0.125,setosa
17,5.1,0.222222,3.500000,0.625000,1.400000,0.067797,0.30,0.083333333,setosa
18,5.7,0.388889,3.800000,0.750000,1.700000,0.118644,0.30,0.083333333,setosa
19,5.1,0.222222,3.800000,0.750000,1.500000,0.084746,0.30,0.083333333,setosa
20,5.4,0.305556,3.400000,0.583333,1.700000,0.118644,0.20,0.041666667,setosa
21,5.1,0.222222,3.700000,0.708333,1.500000,0.084746,0.40,0.125,setosa
22,4.6,0.083333,3.600000,0.666667,1.000000,0.010000,0.20,0.041666667,setosa
23,5.1,0.222222,3.300000,0.541667,1.700000,0.118644,0.50,0.166666667,setosa
24,4.8,0.138889,3.400000,0.583333,1.900000,0.152542,0.20,0.041666667,setosa
25,5.0,0.194444,3.000000,0.416667,1.600000,0.101695,0.20,0.041666667,setosa
26,5.0,0.194444,3.400000,NaN,NaN,0.101695,0.40,0.125,setosa
27,5.2,0.250000,3.500000,0.625000,1.500000,0.084746,0.20,0.041666667,setosa
28,5.2,0.250000,3.400000,0.583333,1.400000,0.067797,0.20,0.041666667,setosa
29,4.7,0.111111,3.200000,0.500000,1.600000,0.101695,0.20,0.041666667,setosa
30,4.8,0.138889,3.100000,0.458333,1.600000,0.101695,0.20,0.041666667,setosa
31,5.4,0.305556,3.400000,0.583333,1.500000,0.084746,0.40,0.125,setosa
32,7.0,0.750000,3.200000,0.500000,4.700000,0.627119,1.40,0.541666667,versicolor
...,...,...,...,...,...,...,...,...,...
69,6.3,0.555556,2.900000,0.375000,5.600000,0.779661,1.80,0.708333333,virginica
70,6.5,0.611111,3.000000,0.416667,5.800000,0.813559,2.20,0.875,virginica
71,7.6,0.916667,3.000000,0.416667,6.600000,0.949153,2.10,0.833333333,virginica
72,4.9,0.166667,2.500000,0.208333,4.500000,0.593220,1.70,0.666666667,virginica
73,7.3,0.833333,2.900000,0.375000,6.300000,0.898305,1.80,0.708333333,virginica
74,6.7,0.666667,2.500000,0.208333,5.800000,0.813559,1.80,0.708333333,virginica
75,7.2,0.805556,3.600000,0.666667,6.100000,0.864407,2.50,0.9999,virginica
76,6.5,0.611111,3.200000,0.500000,5.100000,0.694915,2.00,0.791666667,virginica
77,6.4,0.583333,2.700000,0.291667,5.300000,0.728814,1.90,0.75,virginica
78,6.8,0.694444,3.000000,0.416667,5.500000,0.762712,2.10,0.833333333,virginica
79,5.7,0.388889,2.500000,0.208333,5.000000,0.677966,2.00,0.791666667,virginica
80,5.8,0.416667,2.800000,0.333333,5.100000,0.694915,2.40,0.958333333,virginica
81,6.4,0.583333,3.200000,0.500000,5.300000,0.728814,2.30,0.916666667,virginica
82,6.5,0.611111,3.000000,0.416667,5.500000,0.762712,1.80,0.708333333,virginica
83,7.7,0.944444,3.800000,0.750000,6.700000,0.966102,2.20,0.875,virginica
84,7.7,0.944444,2.600000,0.250000,6.900000,0.999900,2.30,0.916666667,virginica
85,6.0,0.472222,2.200000,0.083333,5.000000,0.677966,1.50,0.583333333,virginica
86,6.9,0.722222,3.200000,0.500000,5.700000,0.796610,2.30,NaN,virginica
87,5.6,0.361111,2.800000,0.333333,4.900000,0.661017,2.00,0.791666667,virginica
88,7.7,0.944444,2.800000,0.333333,6.700000,0.966102,2.00,0.791666667,virginica
89,6.3,0.555556,2.700000,0.291667,4.900000,0.661017,1.80,0.708333333,virginica
90,6.7,0.666667,3.300000,0.541667,5.700000,0.796610,2.10,0.833333333,virginica
91,7.2,0.805556,3.200000,0.500000,6.000000,0.847458,1.80,0.708333333,virginica
92,6.2,0.527778,2.800000,0.333333,4.800000,0.644068,1.80,0.708333333,virginica
94,6.4,0.583333,2.800000,0.333333,5.600000,0.779661,2.10,0.833333333,virginica
95,7.2,0.805556,3.000000,0.416667,5.800000,0.813559,1.60,0.625,virginica
96,7.4,NaN,0.333333,6.100000,0.864407,1.900000,0.75,virginica,NaN
97,7.9,0.999900,3.800000,0.750000,6.400000,0.915254,2.00,0.791666667,virginica
98,6.4,0.583333,2.800000,0.333333,5.600000,0.779661,2.20,0.875,virginica
99,6.3,0.555556,2.800000,0.333333,5.100000,0.694915,1.50,0.583333333,virginica

In [33]:
df.drop('a', axis=1)

,b,c,d,e,f,g,h,i
0,0.222222,3.500000,0.625000,1.400000,0.067797,0.20,0.041666667,setosa
1,0.166667,3.000000,0.416667,1.400000,0.067797,0.20,0.041666667,setosa
2,0.111111,3.200000,0.500000,1.300000,NaN,0.20,0.041666667,setosa
3,0.083333,3.100000,0.458333,1.500000,0.084746,0.20,0.041666667,setosa
7,0.194444,3.400000,NaN,1.500000,0.084746,0.20,0.041666667,setosa
8,0.027778,2.900000,0.375000,1.400000,0.067797,0.20,0.041666667,setosa
9,0.166667,3.100000,0.458333,1.500000,0.084746,0.10,0.01,setosa
10,0.305556,3.700000,0.708333,1.500000,0.084746,0.20,0.041666667,setosa
11,0.138889,3.400000,0.583333,1.600000,0.101695,0.20,0.041666667,setosa
12,0.138889,3.000000,0.416667,1.400000,0.067797,0.10,0.01,setosa
13,0.010000,3.000000,NaN,1.100000,0.016949,0.10,0.01,setosa
14,0.416667,4.000000,0.833333,1.200000,0.033898,0.20,0.041666667,setosa
15,0.388889,4.400000,0.999900,1.500000,0.084746,0.40,0.125,setosa
16,0.305556,3.900000,0.791667,1.300000,0.050847,0.40,0.125,setosa
17,0.222222,3.500000,0.625000,1.400000,0.067797,0.30,0.083333333,setosa
18,0.388889,3.800000,0.750000,1.700000,0.118644,0.30,0.083333333,setosa
19,0.222222,3.800000,0.750000,1.500000,0.084746,0.30,0.083333333,setosa
20,0.305556,3.400000,0.583333,1.700000,0.118644,0.20,0.041666667,setosa
21,0.222222,3.700000,0.708333,1.500000,0.084746,0.40,0.125,setosa
22,0.083333,3.600000,0.666667,1.000000,0.010000,0.20,0.041666667,setosa
23,0.222222,3.300000,0.541667,1.700000,0.118644,0.50,0.166666667,setosa
24,0.138889,3.400000,0.583333,1.900000,0.152542,0.20,0.041666667,setosa
25,0.194444,3.000000,0.416667,1.600000,0.101695,0.20,0.041666667,setosa
26,0.194444,3.400000,NaN,NaN,0.101695,0.40,0.125,setosa
27,0.250000,3.500000,0.625000,1.500000,0.084746,0.20,0.041666667,setosa
28,0.250000,3.400000,0.583333,1.400000,0.067797,0.20,0.041666667,setosa
29,0.111111,3.200000,0.500000,1.600000,0.101695,0.20,0.041666667,setosa
30,0.138889,3.100000,0.458333,1.600000,0.101695,0.20,0.041666667,setosa
31,0.305556,3.400000,0.583333,1.500000,0.084746,0.40,0.125,setosa
32,0.750000,3.200000,0.500000,4.700000,0.627119,1.40,0.541666667,versicolor
...,...,...,...,...,...,...,...,...
69,0.555556,2.900000,0.375000,5.600000,0.779661,1.80,0.708333333,virginica
70,0.611111,3.000000,0.416667,5.800000,0.813559,2.20,0.875,virginica
71,0.916667,3.000000,0.416667,6.600000,0.949153,2.10,0.833333333,virginica
72,0.166667,2.500000,0.208333,4.500000,0.593220,1.70,0.666666667,virginica
73,0.833333,2.900000,0.375000,6.300000,0.898305,1.80,0.708333333,virginica
74,0.666667,2.500000,0.208333,5.800000,0.813559,1.80,0.708333333,virginica
75,0.805556,3.600000,0.666667,6.100000,0.864407,2.50,0.9999,virginica
76,0.611111,3.200000,0.500000,5.100000,0.694915,2.00,0.791666667,virginica
77,0.583333,2.700000,0.291667,5.300000,0.728814,1.90,0.75,virginica
78,0.694444,3.000000,0.416667,5.500000,0.762712,2.10,0.833333333,virginica
79,0.388889,2.500000,0.208333,5.000000,0.677966,2.00,0.791666667,virginica
80,0.416667,2.800000,0.333333,5.100000,0.694915,2.40,0.958333333,virginica
81,0.583333,3.200000,0.500000,5.300000,0.728814,2.30,0.916666667,virginica
82,0.611111,3.000000,0.416667,5.500000,0.762712,1.80,0.708333333,virginica
83,0.944444,3.800000,0.750000,6.700000,0.966102,2.20,0.875,virginica
84,0.944444,2.600000,0.250000,6.900000,0.999900,2.30,0.916666667,virginica
85,0.472222,2.200000,0.083333,5.000000,0.677966,1.50,0.583333333,virginica
86,0.722222,3.200000,0.500000,5.700000,0.796610,2.30,NaN,virginica
87,0.361111,2.800000,0.333333,4.900000,0.661017,2.00,0.791666667,virginica
88,0.944444,2.800000,0.333333,6.700000,0.966102,2.00,0.791666667,virginica
89,0.555556,2.700000,0.291667,4.900000,0.661017,1.80,0.708333333,virginica
90,0.666667,3.300000,0.541667,5.700000,0.796610,2.10,0.833333333,virginica
91,0.805556,3.200000,0.500000,6.000000,0.847458,1.80,0.708333333,virginica
92,0.527778,2.800000,0.333333,4.800000,0.644068,1.80,0.708333333,virginica
94,0.583333,2.800000,0.333333,5.600000,0.779661,2.10,0.833333333,virginica
95,0.805556,3.000000,0.416667,5.800000,0.813559,1.60,0.625,virginica
96,NaN,0.333333,6.100000,0.864407,1.900000,0.75,virginica,NaN
97,0.999900,3.800000,0.750000,6.400000,0.915254,2.00,0.791666667,virginica
98,0.583333,2.800000,0.333333,5.600000,0.779661,2.20,0.875,virginica
99,0.555556,2.800000,0.333333,5.100000,0.694915,1.50,0.583333333,virginica

In [34]:
df.fillna(0)

,a,b,c,d,e,f,g,h,i
0,5.1,0.222222,3.500000,0.625000,1.400000,0.067797,0.20,0.041666667,setosa
1,4.9,0.166667,3.000000,0.416667,1.400000,0.067797,0.20,0.041666667,setosa
2,4.7,0.111111,3.200000,0.500000,1.300000,0.000000,0.20,0.041666667,setosa
3,4.6,0.083333,3.100000,0.458333,1.500000,0.084746,0.20,0.041666667,setosa
7,5.0,0.194444,3.400000,0.000000,1.500000,0.084746,0.20,0.041666667,setosa
8,4.4,0.027778,2.900000,0.375000,1.400000,0.067797,0.20,0.041666667,setosa
9,4.9,0.166667,3.100000,0.458333,1.500000,0.084746,0.10,0.01,setosa
10,5.4,0.305556,3.700000,0.708333,1.500000,0.084746,0.20,0.041666667,setosa
11,4.8,0.138889,3.400000,0.583333,1.600000,0.101695,0.20,0.041666667,setosa
12,4.8,0.138889,3.000000,0.416667,1.400000,0.067797,0.10,0.01,setosa
13,4.3,0.010000,3.000000,0.000000,1.100000,0.016949,0.10,0.01,setosa
14,5.8,0.416667,4.000000,0.833333,1.200000,0.033898,0.20,0.041666667,setosa
15,5.7,0.388889,4.400000,0.999900,1.500000,0.084746,0.40,0.125,setosa
16,5.4,0.305556,3.900000,0.791667,1.300000,0.050847,0.40,0.125,setosa
17,5.1,0.222222,3.500000,0.625000,1.400000,0.067797,0.30,0.083333333,setosa
18,5.7,0.388889,3.800000,0.750000,1.700000,0.118644,0.30,0.083333333,setosa
19,5.1,0.222222,3.800000,0.750000,1.500000,0.084746,0.30,0.083333333,setosa
20,5.4,0.305556,3.400000,0.583333,1.700000,0.118644,0.20,0.041666667,setosa
21,5.1,0.222222,3.700000,0.708333,1.500000,0.084746,0.40,0.125,setosa
22,4.6,0.083333,3.600000,0.666667,1.000000,0.010000,0.20,0.041666667,setosa
23,5.1,0.222222,3.300000,0.541667,1.700000,0.118644,0.50,0.166666667,setosa
24,4.8,0.138889,3.400000,0.583333,1.900000,0.152542,0.20,0.041666667,setosa
25,5.0,0.194444,3.000000,0.416667,1.600000,0.101695,0.20,0.041666667,setosa
26,5.0,0.194444,3.400000,0.000000,0.000000,0.101695,0.40,0.125,setosa
27,5.2,0.250000,3.500000,0.625000,1.500000,0.084746,0.20,0.041666667,setosa
28,5.2,0.250000,3.400000,0.583333,1.400000,0.067797,0.20,0.041666667,setosa
29,4.7,0.111111,3.200000,0.500000,1.600000,0.101695,0.20,0.041666667,setosa
30,4.8,0.138889,3.100000,0.458333,1.600000,0.101695,0.20,0.041666667,setosa
31,5.4,0.305556,3.400000,0.583333,1.500000,0.084746,0.40,0.125,setosa
32,7.0,0.750000,3.200000,0.500000,4.700000,0.627119,1.40,0.541666667,versicolor
...,...,...,...,...,...,...,...,...,...
69,6.3,0.555556,2.900000,0.375000,5.600000,0.779661,1.80,0.708333333,virginica
70,6.5,0.611111,3.000000,0.416667,5.800000,0.813559,2.20,0.875,virginica
71,7.6,0.916667,3.000000,0.416667,6.600000,0.949153,2.10,0.833333333,virginica
72,4.9,0.166667,2.500000,0.208333,4.500000,0.593220,1.70,0.666666667,virginica
73,7.3,0.833333,2.900000,0.375000,6.300000,0.898305,1.80,0.708333333,virginica
74,6.7,0.666667,2.500000,0.208333,5.800000,0.813559,1.80,0.708333333,virginica
75,7.2,0.805556,3.600000,0.666667,6.100000,0.864407,2.50,0.9999,virginica
76,6.5,0.611111,3.200000,0.500000,5.100000,0.694915,2.00,0.791666667,virginica
77,6.4,0.583333,2.700000,0.291667,5.300000,0.728814,1.90,0.75,virginica
78,6.8,0.694444,3.000000,0.416667,5.500000,0.762712,2.10,0.833333333,virginica
79,5.7,0.388889,2.500000,0.208333,5.000000,0.677966,2.00,0.791666667,virginica
80,5.8,0.416667,2.800000,0.333333,5.100000,0.694915,2.40,0.958333333,virginica
81,6.4,0.583333,3.200000,0.500000,5.300000,0.728814,2.30,0.916666667,virginica
82,6.5,0.611111,3.000000,0.416667,5.500000,0.762712,1.80,0.708333333,virginica
83,7.7,0.944444,3.800000,0.750000,6.700000,0.966102,2.20,0.875,virginica
84,7.7,0.944444,2.600000,0.250000,6.900000,0.999900,2.30,0.916666667,virginica
85,6.0,0.472222,2.200000,0.083333,5.000000,0.677966,1.50,0.583333333,virginica
86,6.9,0.722222,3.200000,0.500000,5.700000,0.796610,2.30,0,virginica
87,5.6,0.361111,2.800000,0.333333,4.900000,0.661017,2.00,0.791666667,virginica
88,7.7,0.944444,2.800000,0.333333,6.700000,0.966102,2.00,0.791666667,virginica
89,6.3,0.555556,2.700000,0.291667,4.900000,0.661017,1.80,0.708333333,virginica
90,6.7,0.666667,3.300000,0.541667,5.700000,0.796610,2.10,0.833333333,virginica
91,7.2,0.805556,3.200000,0.500000,6.000000,0.847458,1.80,0.708333333,virginica
92,6.2,0.527778,2.800000,0.333333,4.800000,0.644068,1.80,0.708333333,virginica
94,6.4,0.583333,2.800000,0.333333,5.600000,0.779661,2.10,0.833333333,virginica
95,7.2,0.805556,3.000000,0.416667,5.800000,0.813559,1.60,0.625,virginica
96,7.4,0.000000,0.333333,6.100000,0.864407,1.900000,0.75,virginica,0
97,7.9,0.999900,3.800000,0.750000,6.400000,0.915254,2.00,0.791666667,virginica
98,6.4,0.583333,2.800000,0.333333,5.600000,0.779661,2.20,0.875,virginica
99,6.3,0.555556,2.800000,0.333333,5.100000,0.694915,1.50,0.583333333,virginica

In [35]:
df.replace(0, 5)

,a,b,c,d,e,f,g,h,i
0,5.1,0.222222,3.500000,0.625000,1.400000,0.067797,0.20,0.041666667,setosa
1,4.9,0.166667,3.000000,0.416667,1.400000,0.067797,0.20,0.041666667,setosa
2,4.7,0.111111,3.200000,0.500000,1.300000,NaN,0.20,0.041666667,setosa
3,4.6,0.083333,3.100000,0.458333,1.500000,0.084746,0.20,0.041666667,setosa
7,5.0,0.194444,3.400000,NaN,1.500000,0.084746,0.20,0.041666667,setosa
8,4.4,0.027778,2.900000,0.375000,1.400000,0.067797,0.20,0.041666667,setosa
9,4.9,0.166667,3.100000,0.458333,1.500000,0.084746,0.10,0.01,setosa
10,5.4,0.305556,3.700000,0.708333,1.500000,0.084746,0.20,0.041666667,setosa
11,4.8,0.138889,3.400000,0.583333,1.600000,0.101695,0.20,0.041666667,setosa
12,4.8,0.138889,3.000000,0.416667,1.400000,0.067797,0.10,0.01,setosa
13,4.3,0.010000,3.000000,NaN,1.100000,0.016949,0.10,0.01,setosa
14,5.8,0.416667,4.000000,0.833333,1.200000,0.033898,0.20,0.041666667,setosa
15,5.7,0.388889,4.400000,0.999900,1.500000,0.084746,0.40,0.125,setosa
16,5.4,0.305556,3.900000,0.791667,1.300000,0.050847,0.40,0.125,setosa
17,5.1,0.222222,3.500000,0.625000,1.400000,0.067797,0.30,0.083333333,setosa
18,5.7,0.388889,3.800000,0.750000,1.700000,0.118644,0.30,0.083333333,setosa
19,5.1,0.222222,3.800000,0.750000,1.500000,0.084746,0.30,0.083333333,setosa
20,5.4,0.305556,3.400000,0.583333,1.700000,0.118644,0.20,0.041666667,setosa
21,5.1,0.222222,3.700000,0.708333,1.500000,0.084746,0.40,0.125,setosa
22,4.6,0.083333,3.600000,0.666667,1.000000,0.010000,0.20,0.041666667,setosa
23,5.1,0.222222,3.300000,0.541667,1.700000,0.118644,0.50,0.166666667,setosa
24,4.8,0.138889,3.400000,0.583333,1.900000,0.152542,0.20,0.041666667,setosa
25,5.0,0.194444,3.000000,0.416667,1.600000,0.101695,0.20,0.041666667,setosa
26,5.0,0.194444,3.400000,NaN,NaN,0.101695,0.40,0.125,setosa
27,5.2,0.250000,3.500000,0.625000,1.500000,0.084746,0.20,0.041666667,setosa
28,5.2,0.250000,3.400000,0.583333,1.400000,0.067797,0.20,0.041666667,setosa
29,4.7,0.111111,3.200000,0.500000,1.600000,0.101695,0.20,0.041666667,setosa
30,4.8,0.138889,3.100000,0.458333,1.600000,0.101695,0.20,0.041666667,setosa
31,5.4,0.305556,3.400000,0.583333,1.500000,0.084746,0.40,0.125,setosa
32,7.0,0.750000,3.200000,0.500000,4.700000,0.627119,1.40,0.541666667,versicolor
...,...,...,...,...,...,...,...,...,...
69,6.3,0.555556,2.900000,0.375000,5.600000,0.779661,1.80,0.708333333,virginica
70,6.5,0.611111,3.000000,0.416667,5.800000,0.813559,2.20,0.875,virginica
71,7.6,0.916667,3.000000,0.416667,6.600000,0.949153,2.10,0.833333333,virginica
72,4.9,0.166667,2.500000,0.208333,4.500000,0.593220,1.70,0.666666667,virginica
73,7.3,0.833333,2.900000,0.375000,6.300000,0.898305,1.80,0.708333333,virginica
74,6.7,0.666667,2.500000,0.208333,5.800000,0.813559,1.80,0.708333333,virginica
75,7.2,0.805556,3.600000,0.666667,6.100000,0.864407,2.50,0.9999,virginica
76,6.5,0.611111,3.200000,0.500000,5.100000,0.694915,2.00,0.791666667,virginica
77,6.4,0.583333,2.700000,0.291667,5.300000,0.728814,1.90,0.75,virginica
78,6.8,0.694444,3.000000,0.416667,5.500000,0.762712,2.10,0.833333333,virginica
79,5.7,0.388889,2.500000,0.208333,5.000000,0.677966,2.00,0.791666667,virginica
80,5.8,0.416667,2.800000,0.333333,5.100000,0.694915,2.40,0.958333333,virginica
81,6.4,0.583333,3.200000,0.500000,5.300000,0.728814,2.30,0.916666667,virginica
82,6.5,0.611111,3.000000,0.416667,5.500000,0.762712,1.80,0.708333333,virginica
83,7.7,0.944444,3.800000,0.750000,6.700000,0.966102,2.20,0.875,virginica
84,7.7,0.944444,2.600000,0.250000,6.900000,0.999900,2.30,0.916666667,virginica
85,6.0,0.472222,2.200000,0.083333,5.000000,0.677966,1.50,0.583333333,virginica
86,6.9,0.722222,3.200000,0.500000,5.700000,0.796610,2.30,NaN,virginica
87,5.6,0.361111,2.800000,0.333333,4.900000,0.661017,2.00,0.791666667,virginica
88,7.7,0.944444,2.800000,0.333333,6.700000,0.966102,2.00,0.791666667,virginica
89,6.3,0.555556,2.700000,0.291667,4.900000,0.661017,1.80,0.708333333,virginica
90,6.7,0.666667,3.300000,0.541667,5.700000,0.796610,2.10,0.833333333,virginica
91,7.2,0.805556,3.200000,0.500000,6.000000,0.847458,1.80,0.708333333,virginica
92,6.2,0.527778,2.800000,0.333333,4.800000,0.644068,1.80,0.708333333,virginica
94,6.4,0.583333,2.800000,0.333333,5.600000,0.779661,2.10,0.833333333,virginica
95,7.2,0.805556,3.000000,0.416667,5.800000,0.813559,1.60,0.625,virginica
96,7.4,NaN,0.333333,6.100000,0.864407,1.900000,0.75,virginica,NaN
97,7.9,0.999900,3.800000,0.750000,6.400000,0.915254,2.00,0.791666667,virginica
98,6.4,0.583333,2.800000,0.333333,5.600000,0.779661,2.20,0.875,virginica
99,6.3,0.555556,2.800000,0.333333,5.100000,0.694915,1.50,0.583333333,virginica

In [36]:
df.replace('.', np.nan)

,a,b,c,d,e,f,g,h,i
0,5.1,0.222222,3.500000,0.625000,1.400000,0.067797,0.20,0.041666667,setosa
1,4.9,0.166667,3.000000,0.416667,1.400000,0.067797,0.20,0.041666667,setosa
2,4.7,0.111111,3.200000,0.500000,1.300000,NaN,0.20,0.041666667,setosa
3,4.6,0.083333,3.100000,0.458333,1.500000,0.084746,0.20,0.041666667,setosa
7,5.0,0.194444,3.400000,NaN,1.500000,0.084746,0.20,0.041666667,setosa
8,4.4,0.027778,2.900000,0.375000,1.400000,0.067797,0.20,0.041666667,setosa
9,4.9,0.166667,3.100000,0.458333,1.500000,0.084746,0.10,0.01,setosa
10,5.4,0.305556,3.700000,0.708333,1.500000,0.084746,0.20,0.041666667,setosa
11,4.8,0.138889,3.400000,0.583333,1.600000,0.101695,0.20,0.041666667,setosa
12,4.8,0.138889,3.000000,0.416667,1.400000,0.067797,0.10,0.01,setosa
13,4.3,0.010000,3.000000,NaN,1.100000,0.016949,0.10,0.01,setosa
14,5.8,0.416667,4.000000,0.833333,1.200000,0.033898,0.20,0.041666667,setosa
15,5.7,0.388889,4.400000,0.999900,1.500000,0.084746,0.40,0.125,setosa
16,5.4,0.305556,3.900000,0.791667,1.300000,0.050847,0.40,0.125,setosa
17,5.1,0.222222,3.500000,0.625000,1.400000,0.067797,0.30,0.083333333,setosa
18,5.7,0.388889,3.800000,0.750000,1.700000,0.118644,0.30,0.083333333,setosa
19,5.1,0.222222,3.800000,0.750000,1.500000,0.084746,0.30,0.083333333,setosa
20,5.4,0.305556,3.400000,0.583333,1.700000,0.118644,0.20,0.041666667,setosa
21,5.1,0.222222,3.700000,0.708333,1.500000,0.084746,0.40,0.125,setosa
22,4.6,0.083333,3.600000,0.666667,1.000000,0.010000,0.20,0.041666667,setosa
23,5.1,0.222222,3.300000,0.541667,1.700000,0.118644,0.50,0.166666667,setosa
24,4.8,0.138889,3.400000,0.583333,1.900000,0.152542,0.20,0.041666667,setosa
25,5.0,0.194444,3.000000,0.416667,1.600000,0.101695,0.20,0.041666667,setosa
26,5.0,0.194444,3.400000,NaN,NaN,0.101695,0.40,0.125,setosa
27,5.2,0.250000,3.500000,0.625000,1.500000,0.084746,0.20,0.041666667,setosa
28,5.2,0.250000,3.400000,0.583333,1.400000,0.067797,0.20,0.041666667,setosa
29,4.7,0.111111,3.200000,0.500000,1.600000,0.101695,0.20,0.041666667,setosa
30,4.8,0.138889,3.100000,0.458333,1.600000,0.101695,0.20,0.041666667,setosa
31,5.4,0.305556,3.400000,0.583333,1.500000,0.084746,0.40,0.125,setosa
32,7.0,0.750000,3.200000,0.500000,4.700000,0.627119,1.40,0.541666667,versicolor
...,...,...,...,...,...,...,...,...,...
69,6.3,0.555556,2.900000,0.375000,5.600000,0.779661,1.80,0.708333333,virginica
70,6.5,0.611111,3.000000,0.416667,5.800000,0.813559,2.20,0.875,virginica
71,7.6,0.916667,3.000000,0.416667,6.600000,0.949153,2.10,0.833333333,virginica
72,4.9,0.166667,2.500000,0.208333,4.500000,0.593220,1.70,0.666666667,virginica
73,7.3,0.833333,2.900000,0.375000,6.300000,0.898305,1.80,0.708333333,virginica
74,6.7,0.666667,2.500000,0.208333,5.800000,0.813559,1.80,0.708333333,virginica
75,7.2,0.805556,3.600000,0.666667,6.100000,0.864407,2.50,0.9999,virginica
76,6.5,0.611111,3.200000,0.500000,5.100000,0.694915,2.00,0.791666667,virginica
77,6.4,0.583333,2.700000,0.291667,5.300000,0.728814,1.90,0.75,virginica
78,6.8,0.694444,3.000000,0.416667,5.500000,0.762712,2.10,0.833333333,virginica
79,5.7,0.388889,2.500000,0.208333,5.000000,0.677966,2.00,0.791666667,virginica
80,5.8,0.416667,2.800000,0.333333,5.100000,0.694915,2.40,0.958333333,virginica
81,6.4,0.583333,3.200000,0.500000,5.300000,0.728814,2.30,0.916666667,virginica
82,6.5,0.611111,3.000000,0.416667,5.500000,0.762712,1.80,0.708333333,virginica
83,7.7,0.944444,3.800000,0.750000,6.700000,0.966102,2.20,0.875,virginica
84,7.7,0.944444,2.600000,0.250000,6.900000,0.999900,2.30,0.916666667,virginica
85,6.0,0.472222,2.200000,0.083333,5.000000,0.677966,1.50,0.583333333,virginica
86,6.9,0.722222,3.200000,0.500000,5.700000,0.796610,2.30,NaN,virginica
87,5.6,0.361111,2.800000,0.333333,4.900000,0.661017,2.00,0.791666667,virginica
88,7.7,0.944444,2.800000,0.333333,6.700000,0.966102,2.00,0.791666667,virginica
89,6.3,0.555556,2.700000,0.291667,4.900000,0.661017,1.80,0.708333333,virginica
90,6.7,0.666667,3.300000,0.541667,5.700000,0.796610,2.10,0.833333333,virginica
91,7.2,0.805556,3.200000,0.500000,6.000000,0.847458,1.80,0.708333333,virginica
92,6.2,0.527778,2.800000,0.333333,4.800000,0.644068,1.80,0.708333333,virginica
94,6.4,0.583333,2.800000,0.333333,5.600000,0.779661,2.10,0.833333333,virginica
95,7.2,0.805556,3.000000,0.416667,5.800000,0.813559,1.60,0.625,virginica
96,7.4,NaN,0.333333,6.100000,0.864407,1.900000,0.75,virginica,NaN
97,7.9,0.999900,3.800000,0.750000,6.400000,0.915254,2.00,0.791666667,virginica
98,6.4,0.583333,2.800000,0.333333,5.600000,0.779661,2.20,0.875,virginica
99,6.3,0.555556,2.800000,0.333333,5.100000,0.694915,1.50,0.583333333,virginica

In [37]:
df[np.random.rand(df.shape[0]) > 0.5] = 1.5
df

,a,b,c,d,e,f,g,h,i
0,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
1,4.9,0.166667,3.000000,0.416667,1.400000,0.067797,0.20,0.041666667,setosa
2,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
3,4.6,0.083333,3.100000,0.458333,1.500000,0.084746,0.20,0.041666667,setosa
7,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
8,4.4,0.027778,2.900000,0.375000,1.400000,0.067797,0.20,0.041666667,setosa
9,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
10,5.4,0.305556,3.700000,0.708333,1.500000,0.084746,0.20,0.041666667,setosa
11,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
12,4.8,0.138889,3.000000,0.416667,1.400000,0.067797,0.10,0.01,setosa
13,4.3,0.010000,3.000000,NaN,1.100000,0.016949,0.10,0.01,setosa
14,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
15,5.7,0.388889,4.400000,0.999900,1.500000,0.084746,0.40,0.125,setosa
16,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
17,5.1,0.222222,3.500000,0.625000,1.400000,0.067797,0.30,0.083333333,setosa
18,5.7,0.388889,3.800000,0.750000,1.700000,0.118644,0.30,0.083333333,setosa
19,5.1,0.222222,3.800000,0.750000,1.500000,0.084746,0.30,0.083333333,setosa
20,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
21,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
22,4.6,0.083333,3.600000,0.666667,1.000000,0.010000,0.20,0.041666667,setosa
23,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
24,4.8,0.138889,3.400000,0.583333,1.900000,0.152542,0.20,0.041666667,setosa
25,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
26,5.0,0.194444,3.400000,NaN,NaN,0.101695,0.40,0.125,setosa
27,5.2,0.250000,3.500000,0.625000,1.500000,0.084746,0.20,0.041666667,setosa
28,5.2,0.250000,3.400000,0.583333,1.400000,0.067797,0.20,0.041666667,setosa
29,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
30,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
31,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
32,7.0,0.750000,3.200000,0.500000,4.700000,0.627119,1.40,0.541666667,versicolor
...,...,...,...,...,...,...,...,...,...
69,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
70,6.5,0.611111,3.000000,0.416667,5.800000,0.813559,2.20,0.875,virginica
71,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
72,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
73,7.3,0.833333,2.900000,0.375000,6.300000,0.898305,1.80,0.708333333,virginica
74,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
75,7.2,0.805556,3.600000,0.666667,6.100000,0.864407,2.50,0.9999,virginica
76,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
77,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
78,6.8,0.694444,3.000000,0.416667,5.500000,0.762712,2.10,0.833333333,virginica
79,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
80,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
81,6.4,0.583333,3.200000,0.500000,5.300000,0.728814,2.30,0.916666667,virginica
82,6.5,0.611111,3.000000,0.416667,5.500000,0.762712,1.80,0.708333333,virginica
83,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
84,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
85,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
86,6.9,0.722222,3.200000,0.500000,5.700000,0.796610,2.30,NaN,virginica
87,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
88,7.7,0.944444,2.800000,0.333333,6.700000,0.966102,2.00,0.791666667,virginica
89,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
90,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
91,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
92,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
94,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
95,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
96,7.4,NaN,0.333333,6.100000,0.864407,1.900000,0.75,virginica,NaN
97,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
98,1.5,1.500000,1.500000,1.500000,1.500000,1.500000,1.50,1.5,1.5
99,6.3,0.555556,2.800000,0.333333,5.100000,0.694915,1.50,0.583333333,virginica

In [38]:
f = lambda df: df.max() - df.min()

In [39]:
df.ix[:,3:5].apply(f) # applying function elementwise

C:\Users\Kasun\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

d    6.090000
e    5.835593
dtype: float64

In [40]:
grouped = df[['a', 'b']].groupby(df['i'])
grouped.mean()

                   a         b
i
1.5         1.500000  1.500000
setosa      4.986667  0.191407
versicolor  6.042857  0.484127
virginica   6.733333  0.675926

In [41]:
grouped = df[['a', 'b']].groupby([df['i'], df['c']]).mean()
grouped.unstack()

              a                                                        ...     \
c           1.5   2.9       3.0  3.1  3.4   3.5  3.6  3.7  3.8  4.4    ...
i                                                                      ...
1.5         1.5   NaN       NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN    ...
setosa      NaN  4.40  4.666667  4.6  5.0  5.15  4.6  5.4  5.4  5.7    ...
versicolor  NaN  6.14  6.300000  6.7  NaN   NaN  NaN  NaN  NaN  NaN    ...
virginica   NaN  7.30  6.725000  NaN  NaN   NaN  7.2  NaN  NaN  NaN    ...

                   b                                                    \
c                3.8       4.4       2.0       2.2       2.4       2.6
i
1.5              NaN       NaN       NaN       NaN       NaN       NaN
setosa      0.305556  0.388889       NaN       NaN       NaN       NaN
versicolor       NaN       NaN  0.194444  0.527778  0.166667  0.388889
virginica        NaN       NaN       NaN       NaN       NaN       NaN


c                2.7       2.8       3.2       3.3
i
1.5              NaN       NaN       NaN       NaN
setosa           NaN       NaN       NaN       NaN
versicolor  0.388889  0.564815  0.750000  0.555556
virginica   0.416667  0.750000  0.652778  0.555556

[4 rows x 36 columns]

In [42]:
df['a'].nunique()

30

In [43]:
df['a'].value_counts() ## count the number of rows with each unique value of variables

1.5    47
6.1     3
5.7     3
6.3     3
5.2     3
5.8     3
6.7     2
5.0     2
6.0     2
6.5     2
4.8     2
6.8     2
6.4     2
4.6     2
4.9     2
5.1     2
6.2     1
5.9     1
7.7     1
7.0     1
7.1     1
5.6     1
5.4     1
6.9     1
7.2     1
7.3     1
4.3     1
6.6     1
4.4     1
7.4     1
Name: a, dtype: int64

In [44]:
df.describe()

,a,b,c,d,e,f,g
count,96.000000,95.000000,96.000000,94.000000,94.000000,96.000000,95.000000
mean,3.754167,0.964725,2.263889,1.028208,2.621962,0.988734,1.331053
std,2.302078,0.557488,0.855155,0.760360,1.683912,0.563251,0.550830
min,1.500000,0.010000,0.333333,0.010000,0.864407,0.010000,0.100000
25%,1.500000,0.458333,1.500000,0.416667,1.500000,0.555085,1.300000
50%,4.350000,0.944444,1.750000,1.500000,1.500000,1.233051,1.500000
75%,6.000000,1.500000,3.000000,1.500000,4.275000,1.500000,1.500000
max,7.700000,1.500000,4.400000,6.100000,6.700000,1.900000,2.500000

In [45]:
df.mean()

a    3.754167
b    0.964725
c    2.263889
d    1.028208
e    2.621962
f    0.988734
g    1.331053
dtype: float64

In [46]:
df.median()

a    4.350000
b    0.944444
c    1.750000
d    1.500000
e    1.500000
f    1.233051
g    1.500000
dtype: float64

In [47]:
df.sort_index().head()

     a         b    c         d    e         f    g            h       i
0  1.5  1.500000  1.5  1.500000  1.5  1.500000  1.5          1.5     1.5
1  4.9  0.166667  3.0  0.416667  1.4  0.067797  0.2  0.041666667  setosa
2  1.5  1.500000  1.5  1.500000  1.5  1.500000  1.5          1.5     1.5
3  4.6  0.083333  3.1  0.458333  1.5  0.084746  0.2  0.041666667  setosa
7  1.5  1.500000  1.5  1.500000  1.5  1.500000  1.5          1.5     1.5

In [48]:
df.plot(kind='bar')
df.plot(kind='hist')
df.boxplot()

In [49]:
# 4.3 Try Out
# 1

In [50]:
lab1ds = pd.read_csv('lab02Exercise01.csv', names = ['a','b','c','d','e'])

In [51]:
lab1ds.shape

(23998, 5)

In [52]:
lab1ds.describe()

                  a             b             c             d             e
count  23998.000000  23998.000000  23998.000000  23998.000000  23998.000000
mean      -0.000130     -0.000304     -0.000511     -0.000308     -0.000776
std        0.024248      0.129312      0.125404      0.055801      0.135187
min       -0.103335     -0.495990     -0.564168     -0.270175     -0.906729
25%       -0.016099     -0.086530     -0.084227     -0.037979     -0.068691
50%       -0.002864     -0.018974     -0.014216     -0.005966     -0.005706
75%        0.012807      0.060714      0.069543      0.031667      0.068963
max        0.317180      1.516013      1.792961      0.821080      1.240835

In [53]:
lab1ds.a[:]

0       -0.022098
1       -0.021707
2        0.000178
3        0.014929
4       -0.000988
5       -0.035786
6       -0.055859
7       -0.046930
8       -0.029292
9       -0.024955
10      -0.030636
11      -0.035159
12      -0.039061
13      -0.047291
14      -0.057911
15      -0.062193
16      -0.057074
17      -0.052835
18      -0.056497
19      -0.061220
20      -0.059505
21      -0.051333
22      -0.044700
23      -0.050683
24      -0.065416
25      -0.069776
26      -0.058093
27      -0.046206
28      -0.045274
29      -0.048852
           ...
23968    0.049910
23969    0.065753
23970    0.072424
23971    0.074372
23972    0.076276
23973    0.076921
23974    0.077258
23975    0.083832
23976    0.098900
23977    0.120208
23978    0.147547
23979    0.175983
23980    0.192549
23981    0.190799
23982    0.178412
23983    0.165612
23984    0.158483
23985    0.165410
23986    0.194925
23987    0.242981
23988    0.290959
23989    0.317180
23990    0.310633
23991    0.281094
23992    0.253460
23993    0.246057
23994    0.260120
23995    0.286042
23996    0.308476
23997    0.314683
Name: a, Length: 23998, dtype: float64

In [54]:
lab1ds.a[1:100]

1    -0.021707
2     0.000178
3     0.014929
4    -0.000988
5    -0.035786
6    -0.055859
7    -0.046930
8    -0.029292
9    -0.024955
10   -0.030636
11   -0.035159
12   -0.039061
13   -0.047291
14   -0.057911
15   -0.062193
16   -0.057074
17   -0.052835
18   -0.056497
19   -0.061220
20   -0.059505
21   -0.051333
22   -0.044700
23   -0.050683
24   -0.065416
25   -0.069776
26   -0.058093
27   -0.046206
28   -0.045274
29   -0.048852
30   -0.048178
        ...
70   -0.014724
71   -0.016640
72   -0.021621
73   -0.027821
74   -0.028388
75   -0.020702
76   -0.011260
77   -0.009039
78   -0.015727
79   -0.025871
80   -0.033621
81   -0.036861
82   -0.037064
83   -0.035915
84   -0.032827
85   -0.027238
86   -0.021823
87   -0.020535
88   -0.023756
89   -0.028099
90   -0.030206
91   -0.028310
92   -0.022440
93   -0.015883
94   -0.012522
95   -0.011500
96   -0.010638
97   -0.011732
98   -0.014864
99   -0.014416
Name: a, Length: 99, dtype: float64

In [ ]:
# 2

In [ ]:
lab2ds = pd.read_csv('lab02Exercise04.csv', names = ['channel1','channel2','channel3','channel4','channel5'])

In [ ]:
lab2ds.describe()

In [ ]:
# 3

In [ ]:
lab2ds.head(1000)

In [ ]:
lab2ds.mean()

In [ ]:
data = lab2ds.fillna(lab2ds.mean())
data.sample(10)

In [ ]:
from pandas.plotting import scatter_matrix
scatter_matrix(data , alpha=0.2, figsize=(6, 6), diagonal='kde')

In [ ]:
# channel1 vs channel1 has a relationship of a bell curve, and each channel with same channel has that kind of relationship
# most channels with other channels has a linear realtionship with each other, for example channel1 vs channel3, channel3 vs channel3
# they are not true linear but we can see them like a linear relationship(they have a noise)
# channel1 and channel5 has some scattering but can be still categorized as a linear relationship

In [ ]:
def pred(row):
    if (row['channel1'] + row['channel5'])/2 < (row['channel2'] + row['channel3'] + row['channel4'])/3:
        return 1
    return 0

In [ ]:
data['class'] = data.apply(lambda row: pred(row),axis=1)
data.sample(10)